<a href="https://colab.research.google.com/github/ItzNotCheetah/Final-Grade-Prediction-Project/blob/main/Final_Grade_Prediction_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Final Grade Prediction Project

# Importing the Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the Dataset

In [ ]:
dataset = pd.read_csv('student-mat.csv', sep= ';')
X = dataset[
    [
        "G1","G2","studytime","failures","absences",
        "age","sex","address","Medu","Fedu",
        "famrel","freetime","goout","health"
    ]
]
y = dataset["G3"]

In [ ]:
print(X)

     G1  G2  studytime  failures  absences  age sex address  Medu  Fedu  \
0     5   6          2         0         6   18   F       U     4     4   
1     5   5          2         0         4   17   F       U     1     1   
2     7   8          2         3        10   15   F       U     1     1   
3    15  14          3         0         2   15   F       U     4     2   
4     6  10          2         0         4   16   F       U     3     3   
..   ..  ..        ...       ...       ...  ...  ..     ...   ...   ...   
390   9   9          2         2        11   20   M       U     2     2   
391  14  16          1         0         3   17   M       U     3     1   
392  10   8          1         3         3   21   M       R     1     1   
393  11  12          1         0         0   18   M       R     3     2   
394   8   9          1         0         5   19   M       U     1     1   

     famrel  freetime  goout  health  
0         4         3      4       3  
1         5         3

# Splitting the Data into Training and Testing Sets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 0)

# Encoding Categorical Data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
categorical_features = ["sex", "address"]
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), categorical_features)], remainder= 'passthrough')
X_train_encoded = ct.fit_transform(X_train)
X_test_encoded = ct.fit_transform(X_test)

X_train_encoded = np.array(X_train_encoded)
X_test_encoded = np.array(X_test_encoded)


In [ ]:
print(X_train_encoded)

[[1. 0. 0. ... 4. 4. 2.]
 [1. 0. 0. ... 3. 4. 2.]
 [1. 0. 0. ... 3. 1. 4.]
 ...
 [0. 1. 0. ... 4. 2. 5.]
 [0. 1. 0. ... 2. 2. 2.]
 [0. 1. 0. ... 4. 4. 5.]]


In [ ]:
print(X_test_encoded)

[[1. 0. 0. ... 3. 3. 4.]
 [1. 0. 1. ... 3. 4. 5.]
 [1. 0. 0. ... 3. 4. 5.]
 ...
 [1. 0. 0. ... 2. 2. 5.]
 [0. 1. 0. ... 5. 3. 5.]
 [1. 0. 0. ... 3. 2. 3.]]


# Training the Multiple Linear Regression Model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train_encoded, y_train)

LinearRegression()

# Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test_encoded)
np.set_printoptions(precision= 2)
y_test_array = y_test.to_numpy()
print(np.concatenate(
    (y_pred.reshape(len(y_pred), 1), y_test_array.reshape(len(y_test_array), 1)),
    axis=1
))

[[13.84 14.  ]
 [10.41 10.  ]
 [ 9.7   9.  ]
 [15.28 15.  ]
 [16.63 16.  ]
 [12.   12.  ]
 [12.65 14.  ]
 [10.45 11.  ]
 [ 8.18  9.  ]
 [14.34 15.  ]
 [ 7.21 10.  ]
 [14.81 11.  ]
 [11.52 10.  ]
 [ 8.1   8.  ]
 [14.73 15.  ]
 [14.47 14.  ]
 [13.   12.  ]
 [ 8.94  0.  ]
 [ 9.42 10.  ]
 [15.21 16.  ]
 [ 6.57  0.  ]
 [ 2.87  0.  ]
 [ 6.21  8.  ]
 [15.33 16.  ]
 [11.68 12.  ]
 [16.17 15.  ]
 [ 9.54 10.  ]
 [20.21 19.  ]
 [-0.14  0.  ]
 [13.4  14.  ]
 [-1.15  0.  ]
 [ 6.72 10.  ]
 [ 7.31  8.  ]
 [ 5.26  4.  ]
 [12.85 13.  ]
 [ 9.88 10.  ]
 [13.1  13.  ]
 [18.72 18.  ]
 [ 8.53  8.  ]
 [11.84 11.  ]
 [ 4.33  6.  ]
 [18.61 18.  ]
 [ 7.06  8.  ]
 [ 8.3   8.  ]
 [10.37 11.  ]
 [-2.08  0.  ]
 [11.91 13.  ]
 [ 3.7   0.  ]
 [11.82 13.  ]
 [ 6.83  7.  ]
 [ 9.51 10.  ]
 [18.68 18.  ]
 [11.74 10.  ]
 [ 7.27  9.  ]
 [12.45 11.  ]
 [ 8.48  6.  ]
 [ 9.02  9.  ]
 [12.28 13.  ]
 [14.95 15.  ]
 [14.02 14.  ]
 [12.84 14.  ]
 [13.12 15.  ]
 [13.93 14.  ]
 [15.62 15.  ]
 [ 7.83  0.  ]
 [16.12 15.  ]
 [18.04 19